# Generated by Django 5.0.6 on 2024-08-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_messages_room_friendslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='main.chatroom'),
        ),
    ]
