# Generated by Django 5.0.6 on 2025-01-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_requestlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlist',
            old_name='Friends_List',
            new_name='Friend_Request_List',
        ),
    ]
